// Generated by CoffeeScript 1.7.1
angular.module("sightApp").directive('authorInputFormatter', function() {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: function(scope, element, attrs, ngModelController) {
      ngModelController.$formatters.push(function(modelValue) {
        if (modelValue != null) {
          return _.pluck(modelValue, 'name').join(', ');
        } else {
          return '';
        }
      });
      return ngModelController.$parsers.push(function(viewValue) {
        return _.map(_.filter(viewValue.split(', '), function(s) {
          return s.length > 0;
        }), function(d) {
          return {
            name: d
          };
        });
      });
    }
  };
});
