// Generated by CoffeeScript 1.7.1
angular.module('sightApp').directive('infoBar', function() {
  return {
    restrict: 'A',
    scope: true,
    templateUrl: 'js/components/info-bar/info-bar.html',
    controller:"InfoBarController",
    controllerAs:"infoBarCtrl"
  };
});
