// Generated by CoffeeScript 1.7.1
angular.module("sightApp").directive('tagInputFormatter', function() {
  return {
    restrict: 'A',
    require: 'ngModel',
    link: function(scope, element, attrs, ngModelController) {
      ngModelController.$formatters.push(function(modelValue) {
        if (modelValue != null) {
          return modelValue.join(', ');
        } else {
          return '';
        }
      });
      return ngModelController.$parsers.push(function(viewValue) {
        return _.filter(viewValue.split(', '), function(s) {
          return s.length > 0;
        });
      });
    }
  };
});
