// Generated by CoffeeScript 1.7.1
angular.module('sightApp').controller('SearchBarController', function($scope) {
  this.allCollections = [
    {
      name: "Thesis",
      count: 10
    }, {
      name: "Projects",
      count: 100
    }, {
      name: "Research",
      count: 99
    }, {
      name: "Others",
      count: 30
    }
  ];
  this.allNames = ['Title', 'Author', 'Year', 'Conference'];
  this.allMeasures = ['>', '<', 'Has', '='];
  this.allConditions = [
    {
      name_id: 0,
      measure_id: 0,
      value: "aoeu"
    }, {
      name_id: 2,
      measure_id: 1,
      value: "aoeuA"
    }, {
      name_id: 3,
      measure_id: 0,
      value: "aoeuAE"
    }, {
      name_id: 0,
      measure_id: 0,
      value: "aoeu"
    }, {
      name_id: 2,
      measure_id: 1,
      value: "aoeuA"
    }, {
      name_id: 3,
      measure_id: 0,
      value: "aoeuAE"
    }
  ];
  return 0;
});
