// Generated by CoffeeScript 1.7.1
angular.module('sightApp').controller('SearchBarController', function($scope, $http) {
  var self;
  self = this;
  this.allCollections = [
    {
      name: "Thesis",
      count: 10
    }, {
      name: "Projects",
      count: 100
    }, {
      name: "Research",
      count: 99
    }, {
      name: "Others",
      count: 30
    }
  ];
  this.allMetrics = [
    {
      name: 'Metric',
      attr: 'unknow'
    }, {
      name: 'Title',
      attr: 'title'
    }, {
      name: 'Author',
      attr: 'author'
    }, {
      name: 'Citation',
      attr: 'cite_count'
    }, {
      name: 'Tag',
      attr: 'tag'
    }, {
      name: 'Location',
      attr: 'location'
    }
  ];
  this.allMeasures = ['Relation', '>', '<', 'Has', '='];
  this.allConditions = [];
  this.removeCondition = function(index) {
    return this.allConditions.splice(index, 1);
  };
  this.addCondition = function() {
    return this.allConditions.push({
      metric_id: 0,
      measure_id: 0,
      value: ""
    });
  };
  this.isConditionTrue = function(d, condition) {
    var data_value, metric_attr, value;
    metric_attr = this.allMetrics[condition.metric_id].attr;
    data_value = d[metric_attr];
    value = condition.value;
    if (metric_attr === 'cite_count') {
      data_value = parseInt(data_value);
      value = parseInt(value);
    }
    if (metric_attr === 'author') {
      data_value = _.pluck(data_value, 'name').join(',');
    }
    switch (this.allMeasures[condition.measure_id]) {
      case '=':
        return data_value === value;
      case '<':
        return data_value < value;
      case '>':
        return data_value > value;
      case 'Has':
        return _.isString(data_value) && (data_value != null) && data_value.indexOf(value) > -1;
    }
  };
  this.search = function() {
    var data, res;
    data = $scope.globalCtrl.tableViewCtrl.allData;
    res = data;
    _.each(self.allConditions, function(condition) {
      return res = _.filter(res, function(d) {
        return self.isConditionTrue(d, condition);
      });
    });
    return $scope.globalCtrl.tableViewCtrl.setData(res);
  };
  return 0;
});
