// Generated by CoffeeScript 1.7.1
angular.module('sightApp').directive('searchBar', function() {
  return {
    restrict: 'E',
    scope: true,
    templateUrl: 'js/components/search-bar/search-bar.html',
    controller: 'SearchBarController',
    controllerAs: 'searchBarCtrl'
  };
});
