// Generated by CoffeeScript 1.7.1
angular.module('sightApp').controller('SearchBarController', function($scope, $http) {
  this.allCollections = [
    {
      name: "Thesis",
      count: 10
    }, {
      name: "Projects",
      count: 100
    }, {
      name: "Research",
      count: 99
    }, {
      name: "Others",
      count: 30
    }
  ];
  this.allNames = ['Metric', 'Title', 'Author', 'Year', 'Conference'];
  this.allMeasures = ['Relation', '>', '<', 'Has', '='];
  this.allConditions = [];
  this.removeCondition = function(index) {
    return this.allConditions.splice(index, 1);
  };
  this.addCondition = function() {
    return this.allConditions.push({
      name_id: 0,
      measure_id: 0,
      value: ""
    });
  };
  this.search = function() {
    var value;
    value = _.isEmpty(this.allConditions) ? '' : this.allConditions[0].value;
    return $http.get($scope.globalCtrl.getServerAddr() + ("?action=search_by_title&title=" + value)).success(function(data) {
      console.log(data);
      return $scope.globalCtrl.tableViewCtrl.setData(data);
    });
  };
  return 0;
});
