// Generated by CoffeeScript 1.7.1
angular.module("sightApp").controller("TableViewController", function($scope, $http) {
  $scope.activeRow = null;
  $scope.setActiveRow = function(row) {
    this.activeRow = row;
    return $scope.globalCtrl.infobarCtrl.setCurrentEntity(row.entity);
  };
  $scope.gridOptions = {
    enableSorting: true,
    columnDefs: [
      {
        field: 'title',
        width: '40%',
        minWidth: 200
      }, {
        field: 'author',
        width: '20%',
        minWidth: 200
      }, {
        name: 'year',
        field: 'pub_year',
        width: '10%',
        maxWidth: 100
      }, {
        field: 'conference',
        width: '30%',
        minWidth: 200
      }
    ],
    rowTemplate: '<div ng-class="{active: grid.appScope.activeRow == row}" ng-click="grid.appScope.setActiveRow(row)" ng-repeat="col in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ui-grid-cell></div>'
  };
  return $http.get('data/publication.json').success(function(data) {
    return $scope.gridOptions.data = data;
  });
});
