// Generated by CoffeeScript 1.7.1
angular.module("sightApp").controller("TableViewController", function($scope, $http) {
  var self;
  self = this;
  $scope.globalCtrl.tableViewCtrl = this;
  this.activeRowEntity = null;
  this.setActiveRow = function(entity) {
    this.activeRowEntity = entity;
    return $scope.globalCtrl.infobarCtrl.setCurrentEntity(entity);
  };
  this.addEmptyRow = function() {
    var newEntity;
    newEntity = {};
    this.gridOptions.data.push(newEntity);
    return this.setActiveRow(newEntity);
  };
  this.gridOptions = {
    enableSorting: true,
    columnDefs: [
      {
        field: 'title',
        width: '40%',
        minWidth: 200
      }, {
        field: 'author',
        width: '20%',
        minWidth: 200
      }, {
        name: 'year',
        field: 'pub_year',
        width: '10%',
        maxWidth: 100
      }, {
        name: 'Citation Count',
        field: 'cite_count',
        width: '10%',
        minWidth: 200
      }, {
        name: 'ISBN/DOI',
        field: 'ISBN',
        width: '30%',
        minWidth: 200
      }
    ],
    rowTemplate: '<div ng-class="{active: grid.appScope.tableViewCtrl.activeRowEntity == row.entity}" ng-click="grid.appScope.tableViewCtrl.setActiveRow(row.entity)" ng-repeat="col in colContainer.renderedColumns track by col.colDef.name" class="ui-grid-cell" ui-grid-cell></div>'
  };
  $http.get('data/publication.json').success(function(data) {
    return self.gridOptions.data = data.slice(0, 5);
  });
  return 0;
});
