// Generated by CoffeeScript 1.7.1
angular.module("sightApp").controller("TableViewController", function($scope) {
  console.log($scope);
  return $(".table-view-container table").colResizable({
    liveDrag: true
  });
});
