// Generated by CoffeeScript 1.7.1
angular.module('sightApp').controller("GlobalController", function($scope) {
  this.tabIndex = 0;
  this.infoBarCtrl = null;
  this.tableViewCtrl = null;
  this.getServerAddr = function() {
    return "http://192.168.0.103:8888/sight-of-cite/back-end/api.php";
  };
  this.addNewPublication = function() {
    return this.tableViewCtrl.addEmptyRow();
  };
  this.removeSelectedPublication = function() {
    return this.tableViewCtrl.removeActiveRow();
  };
  return 0;
});
