// Generated by CoffeeScript 1.7.1
angular.module('sightApp').controller("GlobalController", function($scope) {
  this.tabIndex = 0;
  this.infoBarCtrl = null;
  this.getServerAddr = function() {
    return "http://127.0.0.1:3000/";
  };
  return 0;
});
