// Generated by CoffeeScript 1.7.1
angular.module('sightApp').directive('tagContainer', function() {
  return {
    restrict: 'E',
    scope: {
      entity: '='
    },
    templateUrl: 'js/components/tag-container/tag-container.html'
  };
});
