// Generated by CoffeeScript 1.7.1
angular.module('sightApp').controller('GraphController', function() {
  var margin, svg;
  console.log('here');
  margin = {
    top: 10,
    right: 10,
    bottom: 10,
    left: 10
  };
  svg = d3.select('svg').selectAll('g').attr('transform', 'translate#{margin.left},#{margin.top})');
  return svg.append('circle').attr('cx', 100).attr('cy', 100).attr('r', 20).style('fill', '#000');
});
