// Generated by CoffeeScript 1.7.1
angular.module('sightApp').directive('Graph', function() {
  return {
    restrict: 'E',
    scope: true,
    templateUrl: 'js/components/graph.html',
    controller: 'GraphController',
    controllerAs: 'graphCtrl'
  };
});
