// Generated by CoffeeScript 1.7.1
angular.module('sightApp').directive('headerBar', function() {
  return {
    restrict: 'E',
    scope: true,
    templateUrl: 'js/components/header-bar/header-bar.html'
  };
});
